# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "steps"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Crowd Favorite"]
  s.date = "2013-07-11"
  s.description = "A way to simplify the output of shell scripting written in ruby.\n\nIntegrates with Capistrano and Rake tasks.\n"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/steps.rb",
    "lib/steps/output.rb",
    "lib/steps/spinner.rb",
    "lib/steps/version.rb",
    "steps.gemspec",
    "test.rb"
  ]
  s.homepage = "http://github.com/crowdfavorite/gem-steps"
  s.licenses = ["Apache 2.0"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Scripting output helper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colored>, [">= 1.2"])
      s.add_runtime_dependency(%q<highline>, [">= 1.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.11"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<colored>, [">= 1.2"])
      s.add_dependency(%q<highline>, [">= 1.6"])
      s.add_dependency(%q<rspec>, ["~> 2.11"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<colored>, [">= 1.2"])
    s.add_dependency(%q<highline>, [">= 1.6"])
    s.add_dependency(%q<rspec>, ["~> 2.11"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

